# Generated by Django 3.0.2 on 2020-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_artical'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
