# Generated by Django 3.0.2 on 2020-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_artical_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
    ]
