# Generated by Django 3.0.2 on 2020-01-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwebcms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='acaImg',
            new_name='avaImg',
        ),
    ]
